### PR TITLE
Update changelog and readme

### PR DESCRIPTION
**Pull request by frederikbosch**
We could release an alpha version 4.0.0-alpha1 with this PR merged. Maybe we can change the default branch to 4.x too.

@harikt I do not think I have access to do that.

### CODE REVIEW

**Comment by harikt** [comment]
Default branch changed to 4.x  .

**Comment by frederikbosch** [comment]
Cool, thanks. You want me to do the release? Or will you do it? I read Paul's suggestion to use producer. I have no idea how you are doing this.

**Comment by harikt** [comment]
Can we have a 3.x to 4.x upgrade note ? Regarding releasing alpha I am good with it. Do you mean you are unable to do that ? 

@pmjones suggested to go with http://getproducer.org/ for 4.x release. If you can move forward, else I will look into it. Haven't tried my hands dirty for a while and got a bit busy with many other stuffs.

**Comment by harikt** [comment]
> You want me to do the release? Or will you do it? 

I will be happy if you can. :+1: 

NB : I missed your comment for I was also typing and posting.

**Comment by frederikbosch** [comment]
Cool, I will figure out how to release. I do have one question though. What is a release supposed to do besides creating a tag (and consequently update packagist)?

**Comment by harikt** [comment]
> What is a release supposed to do besides creating a tag (and consequently update packagist)?

You don't want to manually create a tag nor update anything on packagist.

1. Install producer 
1. Configure producer for first time
1. producer phpdoc
1. producer validate 4.0.0-alpha1
1. producer release 4.0.0-alpha1

I hope that's all :-) .

**Comment by harikt** [comment]
There is a few things we need to update in README . Please look into it.

**Comment by frederikbosch** [comment]
Will change that and add the migrating note. Regarding the community info, is that still correct? I am not using any of these myself.

**Comment by harikt** [comment]
> To ask questions, provide feedback, or otherwise communicate with other Aura users, please join our 

1. Google Group : Yes
1. follow @auraphp : not sure, pmjones handle this
1. chat with us on Freenode in the #auraphp channel. : I sometimes used to login, but lately not using.
1. stackoverflow : Yes.

**Comment by frederikbosch** [comment]
Release is there.

**Comment by frederikbosch** [comment]
Thanks for the help with this @harikt

**Comment by harikt** [comment]
You are welcome. Now you can notify google groups regarding this and make a tweet on your behalf. We can retweet :) .

**Pull request merged**
