### PR TITLE
Allow null as a parameter value

### PR DESCRIPTION
**Pull request by dstockto**
Fix for 3.x branch for issue #99

### CODE REVIEW

**Comment by harikt** [comment]
Hey @dstockto, 

Thanks for the PR. Will you able to send a test also, so if some else change the code it don't break this behaviour? 

Thank you.

**Comment by dstockto** [comment]
Yeah, I can look into doing that @harikt - probably later tonight or something though. I'm relying on you guys though to make sure it's not doing anything stupid since I don't use the library at this time.

**Comment by dstockto** [comment]
@harikt I've added tests for the 3 different cases that changed - explicit named, explicit position based and implicit named (inherited) parameters.

**Comment by pmjones** [comment]
Thanks guys!

**Pull request merged**
