### PR TITLE
Improvements to trait handling

### PR DESCRIPTION
**Pull request by djmattyg007**
This PR contains improvements discussed on issue #43.

### CODE REVIEW

**Comment by pmjones** [comment]
This looks good! If you could, please add a test for it as well, then I can merge it.

**Comment by djmattyg007** [comment]
I knew there was something I'd forgotten! Will do.

**Comment by pmjones** [comment]
Thanks!

**Comment by harikt** [comment]
:+1:  now you find your place at http://auraphp.com/contributors/

**Pull request merged**
