### PR TITLE
some touches suggested by @cordoval. fixes #66

### PR DESCRIPTION
**Pull request by pmjones**

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones for 5.3 the assertion test need to be skipped.

**Comment by pmjones** [comment]
how come?

**Comment by pmjones** [comment]
oh god the trait of course :-/

**Comment by pmjones** [comment]
@harikt I think all has been addressed. Cf. commits https://github.com/auraphp/Aura.Di/commit/26a92d200bb672b22f9fe083e636a557bbe0cf0a and https://github.com/auraphp/Aura.Di/commit/fefbd992e5f7ce4e01b6e9e6bba27587939475d1

**Pull request merged**
