### PR TITLE
Disabling autoresolve by default.

### PR DESCRIPTION
**Pull request by brandonsavage**
Discussion over https://groups.google.com/d/msg/auraphp/DEu2mDmJ_dg/GgIaa997VVwJ

### CODE REVIEW

**Comment by harikt** [comment]
Adding a feedback from twitter https://twitter.com/donatj/status/539806052154220545

> @harikt @brandonsavage Personally, I never liked auto resolution so off is good, removed is better.

**Comment by Grummfy** [comment]
:+1: for disabled by default but only on 2.2 to let people not too scary...

**Comment by cxj** [comment]
This seems like a sensible change to me.

**Comment by pmjones** [comment]
I hate auto-resolve. Hate it. But to change the default flag from "auto-resolve" to "do not auto-resolve" is a BC break for existing code. Yes, users can change their code to turn auto-resolution back on, but the fact that they have to make the change at all indicates a break in previously-expected functionality. So until we do version 3, the hated auto-resolution has to stay on by default.

I say again, adding auto-resolution was the worst mistake I ever made in this package, maybe in any Aura package.

**Comment by harikt** [comment]
@pmjones I had a feeling earlier it was bad. But I don't think it was the worst one, for I still love that feature and I always remember the problem that it will bring ;) .

**Pull request closed without merging**
