### PR TITLE
Syntax highlight using GitHub Flavored Markdown

### PR DESCRIPTION
**Pull request by yuya-takeyama**
Here's the preview.
https://github.com/yuya-takeyama/Aura.Di/blob/2f3952ae769ccbdfad9d60700ed2f1a4826a6f25/README.md

If you prefer this style, I'll send more Pull Reqs for also the other packages.

### CODE REVIEW

**Comment by harikt** [comment]
Thank you @yuya-takeyama . I am wondering how this will work for gh-pages.

Will this make any issues ? Do you know for we have something like this rendered in gh-pages .

http://auraphp.github.com/Aura.Di/version/1.0.0-beta2/

Probably we want to try that too. What do you think @pmjones

**Comment by yuya-takeyama** [comment]
I applied same change to gh-pages branch but got failure...
https://help.github.com/articles/pages-don-t-build-unable-to-run-jekyll

GitHub Pages is using [Jekyll](https://github.com/mojombo/jekyll), so another syntax is required.

Below syntax works.

```
{% highlight php %}
<?php
use Aura\Di\Container;
use Aura\Di\Forge;
use Aura\Di\Config;
$di = new Container(new Forge(new Config));
{% endhighlight %}
```

Above is converted like below.

```
<div class='highlight'><pre><code class='php'><span class='cp'>&lt;?php</span>
<span class='k'>use</span> <span class='nx'>Aura\Di\Container</span><span class='p'>;</span>
<span class='k'>use</span> <span class='nx'>Aura\Di\Forge</span><span class='p'>;</span>
<span class='k'>use</span> <span class='nx'>Aura\Di\Config</span><span class='p'>;</span>
<span class='nv'>$di</span> <span class='o'>=</span> <span class='k'>new</span> <span class='nx'>Container</span><span class='p'>(</span><span class='k'>new</span> <span class='nx'>Forge</span><span class='p'>(</span><span class='k'>new</span> <span class='nx'>Config</span><span class='p'>));</span>
</code></pre>
</div>
```

It requires another style sheet to highlight.

Is another change required for your release process?

Seems more issues are made than my first thought... sorry.

**Comment by harikt** [comment]
@yuya-takeyama Thank you for checking the issues.
Currently the gh-pages has no highlighting and if it needs one more css we need to edit all the repo and include the css for default layout.
I will wait for @pmjones confirmation whether its really worth .
No issues are made . You did the right thing giving PR . Lets see where it goes. So no more sorry :D .

**Comment by harikt** [comment]
@pmjones do you think we need to make the changes to all the other Aura.Packages ?

Also please check the gh-pages to see if we have any issues .

**Pull request merged**
