### PR TITLE
Allow values to be lazy by resolving lazies in LazyValue class

### PR DESCRIPTION
**Pull request by djmattyg007**

### CODE REVIEW

**Comment by djmattyg007** [comment]
I would greatly appreciate it if you could tag a new release after this PR is merged, as I have a couple of projects waiting on some of the patches I've supplied.

**Comment by harikt** [comment]
@djmattyg007 I probably didn't understand what is the real use case of this.

Lets ping @pmjones and see if he have some time to tag and release things. I also believe a release is good looking at #136 .

**Comment by djmattyg007** [comment]
The best use-case for this is that one provider configures a service to accept a lazy value, but it doesn't care where that value comes from, and then another provider configures a lazy value that comes from a different service that it provides (that is also not known at the time of DI configuration).

**Comment by pmjones** [comment]
@djmattyg007 Is this pretty much the same as #128?

**Pull request merged**
