### PR TITLE
some touches

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | n |
| New Feature? | n |
| BC Breaks? | n |
| Deprecations? | n |
| Tests Pass? | n |
| Fixed Tickets |  |
| License | MIT |
| Doc PR |  |

 Sent using [Gush](https://github.com/gushphp/gush)

### CODE REVIEW

**Comment by pmjones** [comment]
Apparently the tests fail on this one @cordoval. Can you run the tests locally to make sure all is well?

**Comment by cordoval** [comment]
ok @pmjones

**Comment by harikt** [comment]
@pmjones traits test ;) .

Skip https://travis-ci.org/auraphp/Aura.Di/jobs/35309381#L30 ?

**Comment by cordoval** [comment]
@pmjones is a trait usage that fails on 5.3, should i remove?

**Comment by cordoval** [comment]
ok i will skip on 5.3

**Comment by harikt** [comment]
aah @pmjones the build started to fail from #63 .

https://travis-ci.org/auraphp/Aura.Di/builds/34293311 

Haven't noticed nor I got any errors by email.

**Comment by cordoval** [comment]
@pmjones took care of it, is good to merge. :+1:

**Comment by harikt** [comment]
@cordoval nope I strongly disagree with removing the test entirely.

**Comment by cordoval** [comment]
I will do another PR on aura cli as it seems this is needed.

**Comment by cordoval** [comment]
@harikt read well I am not removing the test entirely. Completely the opposite, I am moving the methods out of the trait into the class. I just need one more PR. hold on a sec.

**Comment by harikt** [comment]
I am in favour of https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests.skipping-tests 

``` php
<?php
/**
 * @requires extension mysqli
 */
class DatabaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @requires PHP 5.3
     */
    public function testConnection()
    {
        // Test requires the mysqli extension and PHP >= 5.3
    }

    // ... All other tests require the mysqli extension
}
```

**Comment by cordoval** [comment]
I know it can be skipped, what I am trying to see is if it is really worth it. I believe just a base class would do and we don't have to do annotations nowhere. Traits make little sense in this context since the usage is simple.

**Comment by pmjones** [comment]
The trait is in fact needed; other integration tests in other packages make use of it.

**Comment by cordoval** [comment]
we can switch that to a base class to avoid having to do special cases just because that. Also it is only used in cli afaik. And we can PR there too to use the base class coming up.

**Comment by cordoval** [comment]
@pmjones good to go now, I will PR the other instances of usage if need be. related https://github.com/auraphp/Aura.Cli/issues/40

**Comment by pmjones** [comment]
Hi @cordoval -- moving the ContainerAssertionsTrait in this way is just not going to work for me. I have applied the remainder of the touches, though.

**Pull request closed without merging**
