### PR TITLE
Non-existent setters detection

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
If setter method not exists, throw SetterMethodNotFound exception

### CODE REVIEW

**Comment by MAXakaWIZARD** [comment]
Damn, again mess with whitespace... How can i fix that? I think this is tabs-related.

**Comment by harikt** [comment]
@MAXakaWIZARD which editor are you using ?

**Comment by MAXakaWIZARD** [comment]
I use PhpStorm

**Comment by koriym** [comment]
maybe "Editor > Other > Strip trailing space on Save" ?

**Comment by harikt** [comment]
As @koriym mentions, I just did a google search on it, probably these links help you if it is so. I have not used Phpstorm myself to comment on it :) . Thank you @koriym .

http://stackoverflow.com/questions/9523801/phpstorm-i-can-click-on-white-space-even-after-a-line-has-finished-i-dont-wa

http://devnet.jetbrains.com/thread/435675;jsessionid=F8850CFA3991239170118B53FD81CC27

**Comment by MAXakaWIZARD** [comment]
Trailing space is not a problem at all. But anyway "Strip trailing space on Save" is set to "All"

**Comment by pmjones** [comment]
The spaces thing, while not critical, makes it very hard to figure out at-a-glance where the "real" changes are. @MAXakaWIZARD if you can you should probably turn off the "Strip trailing space on Save" object so this doesn't happen again.  In the mean time, I am going to make the non-whitespace changes by hand, and then close this pull request and the related issue.

**Comment by pmjones** [comment]
Fix applied in https://github.com/auraphp/Aura.Di/commit/a654c9ea42f74b54739ed79afb3d0ebe3064fa47

**Pull request closed without merging**
