### PR TITLE
add autoload section to composer.json

### PR DESCRIPTION
**Pull request by koriym**
It enable to generate proper autoload file. (vendor/.composer/autoload_namespaces.php )

### CODE REVIEW

**Comment by harikt** [comment]
@koriym Thank you for the pull request . But we are no longer creating the json manually .
The json is been created by release, so we want to make a patch at https://github.com/auraphp/release/blob/master/package.php#L384 .

**Comment by harikt** [comment]
@pmjones any other thoughts on this ?

**Comment by koriym** [comment]
@harikt Ok, I see. 

I leave the info here for other users who want to use Aura.Di standalone with composer install and /vendor/.composer/autoload.php.

```
"autoload": {
    "psr-0": {
        "Aura\\Di": "vendor/Aura/Di/src/"
    }
}
```

**Comment by harikt** [comment]
Don't feel wrong on closing it.
I am sure ie a good one, but as we work with release we need to make the
necessary changes there.
More patches for any components if anything is wrong is welcome :-) .
Thank you once again for making reminding about it .

**Comment by koriym** [comment]
I will do it.
Keep up the good work. Cheers.

**Pull request closed without merging**
