### PR TITLE
Explicit inheritance only

### PR DESCRIPTION
**Pull request by adriengibrat**
Hi,

As I said in https://groups.google.com/d/msg/auraphp/OBbGxJvZcho/KSip3TAek4gJ
I does not seems normal to inherit of default value of parents.

My real goal is to add automatic resolution of type hinted arguments, it does not seems normal to inherit of that either. So I changed inheritance of constructor params to explicit params only (params defined in the DI).

There are also some other small changes before that (fix docblock and use containerInterface in the factory)

I tried to do atomic commits, so you can pick what you want and see the process i've followed.

### CODE REVIEW

**Comment by harikt** [comment]
test failure in travis for hhvm . https://travis-ci.org/auraphp/Aura.Di/jobs/18245748#L34

**Comment by adriengibrat** [comment]
ReflectionParam::__toString is not implemented before HHVM-2.4.0 and Travis is using HHVM-2.3.2
See https://github.com/facebook/hhvm/commit/39a5e928aae9c07f27a880f194d17ce0d38be69e

And the most funny part is that the implementation is different (better) from Zend !
Will be hard to support both implementations...

Anyway, this commit is not really part of "Explicit inheritance only" patch... it's more what I want to achieve in the end, see #29 

Should I repropose a cleaner PR with only the "Explicit inheritance only" part?

i.e Do you agree on the principle that only explicit parents params should be inherited ?

**Comment by adriengibrat** [comment]
I've cleaned up (using rebase) the branch and pushed it (forced) again.
For the record, the original branch is in https://github.com/adriengibrat/Aura.Di/tree/explicit_inheritance_only_and_automatic_type_hint_resolution
I gonna work on automatic type hint resolution whithout forgetting to check travis in the appropriate issue  #29

**Comment by pmjones** [comment]
Hi @adriengibrat -- only just now getting around to reviewing this.

(1)

On one hand, I completely understand why one would want to honor only explicit params/setters (i.e., non-inherited). There is at least one "good practice" reason behind it, maybe more.

On the other hand, I think it's one of the strengths of Aura.Di that it honors parent class params/setters, and that they are overridable by child classes. It seems natural to me that a default value in a parent (e.g. a property or a method argument) would be inherited by a child, unless overridden by that child, and the inheritance of params/setters It's something we've had for a while and it does not appear to be terribly non-performant (at least not in the limited benchmarking I've done). There are other projects that depend on the honoring of inherited params as well.

Overall, I am reluctant to remove the heritability of params/setters/etc.

(2)

The automatic resolution of type hinted params sounds interesting. In the past I have thought of that as being just a little too magical, but I am willing to review any PR you might send along.

**Comment by harikt** [comment]
> The automatic resolution of type hinted params sounds interesting.

I wonder whether this feature was requested by @koriym to send a PR and later moved as Ray.Di . or am I missing something ?

**Comment by pmjones** [comment]
@koriym ^^ ??

**Comment by koriym** [comment]
@harikt No, I don't send PR for that.
 I made ~~Aura.Di~~ Ray.Di because
- I thought @pmjones is not a fan of automatic resolution DI. 
- The best DI system design for me at that moment is Google Guice, Also the best impelemented DI in PHP was Aura.Di, My idea is simply implement Guice subest in PHP with Aura.Di basis.
- (I wanted AOP functionality.)

**Comment by harikt** [comment]
@koriym I think 

> I made Aura.Di because

you were pointing to Ray.Di. And thank you for clarifying.

**Comment by pmjones** [comment]
@koriym, you said:

> I thought @pmjones is not a fan of automatic resolution DI.

I'm not. :-) But, I'm willing to review a PR if it comes in.

**Comment by koriym** [comment]
@harikt Sorry I made confuse.

> I made Aura.Di because

should be I made Ray.Di :(

**Comment by koriym** [comment]
@pmjones ;-) Ok
@harikt Thank you for remembering `Ray.Di`

**Comment by harikt** [comment]
@koriym if I remember Aura.Di I always recall Ray.Di for it has made a lot of adoption and promotion for @auraphp . Thank you.

**Comment by pmjones** [comment]
@adriengibrat So, implicit inheritance of params/setter values is here to stay. I know that's in opposition to this pull request.  If you want to present a separate PR regarding an explicit way of mapping concrete instances to use for specific interface type hints (whether as services or new instances) I'd be happy to review it.

**Pull request closed without merging**
