### PR TITLE
Contextual parameters

### LINKED ISSUE #160: Does Aura.Di have an equiv. to Laravel's "contextual binding"?
Laravel's container supports what they call "Contextual Binding" where you can specify different values for constructor parameter resolution on an instance depending on where the instance is being used.

I recently ran into a need for this when writing some RabbitMQ code. I had a class that handled publishing data to an exchange and I wanted to use 2 instances of this class in different places in my code but in each place I wanted to provide an 'exchange' object instance that was instantiated with a different exchange name string.

If there is no similar functionality already, I thought a possibly easy to use generic approach would be the ability to set named keys on a specified class, like we do for parameter defining, but which have the extra feature that they 'percolate down' until they are consumed.

For instance: class `A` needs an instance of class `B` and this class `B` then needs an instance of class `C`. The constructor for class `C` has a constructor parameter called `exchangeName`. You could defined class `A` as having a key of `exchangeName` with a value of *foo* and when an instance of `A` is created, the instance of class `C` receives the value of *foo* on it's constructor for the parameter `exchangeName`.

This way, if both class `A` and class `D` need instances of class `B` with different values of `exchangeName` for class `C` this is easy to setup.

### PR DESCRIPTION
**Pull request by frederikbosch**
1. Will fix #160 
2. Work in progress, refactored a bit, so now I can actually add the contextual parameters better.
3. Moved all the unified `params`, `setters`, `mutations` and soon `contextualParams` to a `Blueprint` class

### CODE REVIEW

**Comment by frederikbosch** [comment]
The PR is finished in the sense that it fixed #160. The syntax to use contextual binding is as follows.

```
$di->params[D::class]['param'] = $di->lazyNew(B::class)->withContext(new Blueprint(C::class, ['name' => 'second']));
```

This consists of some optimizations.

1. Construction of an object is now centralized into a `Blueprint`. It contains all the specific params/setters/mutations for the class to be instantiated. Before, two class did the same thing.
2. Blueprints can be merged with each other. This allowed the merge methods of the `Resolver` to be moved into the `Blueprint`. This results in a more dedicated `Resolver` class.
3. `LazyInterface` instances are resolved in the final stage of instantiating the object
4. Checks for missing params are now located in one place (the blueprint).

**Comment by frederikbosch** [comment]
Travis fails due to `nightly` is PHP 8.0.0 already, and PHPUnit requires 7.x.

**Comment by frederikbosch** [comment]
Tests fixed

**Comment by frederikbosch** [comment]
I’d be very happy if there could be some feedback. Then we can move to an alpha stage maybe.

**Comment by frederikbosch** [comment]
@harikt Are you OK to merge this in? I stashed the PR, added docs.

**Comment by harikt** [comment]
I will check it on the coming days.

**Comment by harikt** [comment]
@frederikbosch I am good with this.

**Pull request merged**
