### PR TITLE
Adds a type hint option for the type hinting of objects from the container.

### PR DESCRIPTION
**Pull request by brandonsavage**
Part of Dependency Injection is the ability to type hint for a particular object. Using the DI object makes it possible that a particular key will be set, but not contain the object that the requester expects. This will lead to fatal errors and would be best handled through type hinting the object.

This patch raises an exception when the type hint fails. The type hint is optional, and is evaluated only on the get() method since other methods allow for specifying the object that you want to create/get back.

### CODE REVIEW

**Comment by pmjones** [comment]
If we're going to do this, we probably need to typehint lazyGet() as well.

Having said that, I am a little wary here. In strict DI, the typehint it on the method param being injected, and the injected object is checked at the time of the method call, not at the time it is extracted from the DI container. 

As such, I can see this being useful only in a ServiceLocator scenario. Is that the use-case you had in mind, or was it something else?

**Comment by harikt** [comment]
@brandonsavage @pmjones I feel it is good to have type hint. So when an object of the type is not called, we know that.

Earlier some months back, I recall I have also tweeted regarding the same problem. And I feel the need, and as it does not break any backward compatibility it will be good to merge ?

**Comment by koriym** [comment]
> As such, I can see this being useful only in a ServiceLocator scenario. Is that the use-case you had in mind,

Agreed. I think we don't need to touch the container in runtime (outside bootsrap).  But  it will be helpful for those who use the container as SL in runtime. And I also think it will increase readability.

**Comment by brandonsavage** [comment]
I was intentionally using this as a service locator. Of course, this is a DI container. Part of what Paul and I discussed is the fact that the DI container with the type hint makes it far too easy to use it as an SL all the time. Of course, it might be worthwhile to add a SL to the package, or to write a separate SL package.

**Comment by harikt** [comment]
Thank you @brandonsavage . I had a look into the logs :) .

**Comment by pmjones** [comment]
I would prefer to see a separate (perhaps extended) ServiceLocator class rather than add SL stuff into the DI container. (I would prefer not doing SL at all as a library; locators are super-easy to build and in my opinion they belong in the library they are locating for.)

**Pull request closed without merging**
