### PR TITLE
Make it possible to serialize the Aura.Di container

### PR DESCRIPTION
**Pull request by brandonsavage**

### CODE REVIEW

**Comment by brandonsavage** [comment]
@pmjones This should make caching possible.

**Comment by brandonsavage** [comment]
FWIW this improves the performance of Aura.DI 25% with APC. But it has the drawback that closures cannot be serialized.

**Comment by harikt** [comment]
@brandonsavage https://github.com/jeremeamia/super_closure , may caching can be made to a separate bundle ? if we could not bring super_closure ?

**Comment by brandonsavage** [comment]
It was @pmjones desire to make caching possible with the DI container.
Assuming that nobody uses a closure for constructing their components, they
can serialize the container with this change. We can make it a known issue
that closures can't be serialized, and let users make their own decisions.

**Comment by harikt** [comment]
@brandonsavage I don't know whether that is true for all. But in my case I am using. Eg : https://github.com/cocoframework/Cocoframework.Web_Project/blob/caf49b6e3398bbabe9a664a680b3826438271c0a/config/Common.php#L48-L50 as asked at   https://groups.google.com/d/msg/auraphp/myU1o4dkYsU/eu_GfO4qvtYJ

**Comment by brandonsavage** [comment]
The fact that one feature of Aura might not be compatible with another surely isn't a reason to not do it. In your case you simply wouldn't serialize. If Aura's components are truly decoupled then what we do here and what we do there should be independent decisions. 

If developers need closures we can point them in the direction of SuperClosure.

**Comment by harikt** [comment]
> The fact that one feature of Aura might not be compatible with another surely isn't a reason to not do it

Sorry if you misunderstood me. I was not saying don't do it. I was talking about the issues that can happen.

Thanks!

**Comment by pmjones** [comment]
Fails on 5.3 but whatever, I can clean that up.

**Pull request merged**
