### PR TITLE
Update for modern PHP

### PR DESCRIPTION
**Pull request by cxj**
Updates to make compatible with PHP 7.4 and PHPUnit 8+.

### CODE REVIEW

**Comment by frederikbosch** [comment]
You did not update the `require-dev` right?

**Comment by cj-clx** [comment]
@frederikbosch That's correct; I did not.  The changes are backward compatible with PHPUnit 7.

**Comment by frederikbosch** [comment]
For require-dev I think it is fine to just move to the latest version. You?

**Comment by cxj** [comment]
(Sorry for any confusion I may cause with switching between my 2 GitHub accounts, personal and employer).  

* PHPUnit 9 is very new ([release/support dates](https://phpunit.de/supported-versions.html)), and does not support PHP 7.2.  
* PHPUnit 8 is still supported until February, 2021.

Would it perhaps be preferable to update require-dev to version 8?  Or, one could argue for version 9 on the basis that PHP 7.1 hit End-Of-Life for security support on 30 November 2019 and PHP 7.2 likewise hit end of active support on the same date.

**Comment by frederikbosch** [comment]
Oh, yes, I am moving my current projects to PHPUnit 8.

**Comment by cxj** [comment]
I'll attempt to re-roll this PR with an update to `require-dev` for PHPUnit 8, ok?

**Comment by frederikbosch** [comment]
Thanks!

**Comment by cxj** [comment]
Thank _you_ for the quick action!  This will make migrating my web applications to PHP 7.4 that much easier and quicker.

**Pull request merged**
