### PR TITLE
Removing param read-only values, since they are in fact mutable. Fixes #91.

### LINKED ISSUE #91: property-read designation causes PHPStorm to have syntax error
PHPStorm 9 reports that the @property-read designation on the DI properties (params, etc) to be a syntax error.

### PR DESCRIPTION
**Pull request by brandonsavage**

### CODE REVIEW

**Comment by harikt** [comment]
Further looking to merge, I find the commits that introduced for fixing @scrutinizer-ci https://github.com/auraphp/Aura.Di/commit/033fbe9eae64b37d2174fb3e500c1ca202a823ed .

I will wait for @pmjones .

**Comment by harikt** [comment]
Similar one, but https://github.com/auraphp/Aura.Di/pull/103 seems right to go ?

**Comment by brandonsavage** [comment]
They're essentially identical.

**Comment by brandonsavage** [comment]
@pmjones Can we get a decision on merging this?

**Comment by harikt** [comment]
@brandonsavage In this PR I see the @property-read tag removed. But on the other we have @property tag . So may be it will help the @scrutinizer also.

I am not sure though.

**Comment by pmjones** [comment]
Sorry to take so long. Accepting, but may re-introduce other @property tags to soothe Scrutinizer, and to make PHPStorm recognize the that properties at least exist.

**Pull request merged**
