### PR TITLE
Fix return type in phpdoc.

### PR DESCRIPTION
**Pull request by koriym**

### CODE REVIEW

**Comment by harikt** [comment]
This merge went to master, my dear master @pmjones . @koriym for the next PR please make sure you give to `develop` branch.

**Comment by koriym** [comment]
Sorry, it was my mistake.

**Comment by pmjones** [comment]
Crap, I need to pay more attention. Thanks @harikt .

**Comment by harikt** [comment]
no worries @koriym , @pmjones  :) .

**Pull request merged**
